dist: xenial
sudo: true

cache:
  - directories:
      - client/node_modules

matrix:
  include:
    - stage: "Dependencies"
      name: "Installing npm dependencies"
      language: node_js
      node_js: "10.9"
      cache:
        - directories:
            - "client/node_modules"
      before_install:
        - npm install -g @angular/cli@~8.0.6
        - ng --version
        - cd client
      install:
        - npm install
      script: skip
    - stage: "Run tests"
      name: "Client: Testing"
      language: node_js
      node_js: "10.9"
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
      services:
        - xvfb
      install:
        - cd client
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
      script:
        - npm run test-silently

    - name: "Client: Production Build (ES5)"
      language: node_js
      node_js: "10.9"
      install:
        - cd client
        - sed -i '/\"target\"/c\\"target\":\"es5\",' tsconfig.json
      script:
        - npm run build

    - name: "Client: Production Build (ES2015)"
      language: node_js
      node_js: "10.9"
      install:
        - cd client
        - echo "Firefox ESR" > browserslist
      script:
        - npm run build

    - name: "Client: Build"
      language: node_js
      node_js: "10.9"
      script:
        - cd client
        - npm run build-debug

    - name: "Client: Linting"
      language: node_js
      node_js: "10.9"
      script:
        - cd client
        - npm run lint-check

    - name: "Client: Code Formatting Check"
      language: node_js
      node_js: "10.9"
      script:
        - cd client
        - npm list --depth=0 || cat --help
        - npm run prettify-check
